#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 22 22:12:31 2020

@author: radekrehacek
"""

import numpy as np

class NeuralNetwork():
    
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases